CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NULL,
    email VARCHAR(255) UNIQUE NULL,
    password VARCHAR(255) NULL,
    role ENUM('CUSTOMER', 'VENDOR', 'ADMIN') NULL
);
